prefix dbo: <http://dbpedia.org/ontology/>
prefix ex: <http://example.org/ontology/olympics/>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix foaf: <http://xmlns.com/foaf/0.1/>
prefix xsd: <http://www.w3.org/2001/XMLSchema#>

CONSTRUCT {
  # Athlete
  ?uri a foaf:Person ;
      rdfs:label ?Name;
      foaf:gender ?Gender;
      dbo:age ?intAge;
      dbo:height ?intHeight;
      dbo:weight ?decWeight;
      ex:noc ?NOC .
  # Sex
  ?Gender rdfs:label ?genderFull .
}
FROM <file:olympics.csv>
WHERE {
  BIND( "http://example.org/resource/olympics/" AS ?baseURI )

  # Name
  BIND( REPLACE(?Name, "[^a-zA-Z0–9]", "") AS ?NameClean )
  BIND ( URI( CONCAT(?baseURI, "athlete/", ?NameClean) ) AS ?uri )

  # Sex
  BIND ( URI( CONCAT(?baseURI, "gender/", ?Sex) ) AS ?Gender )
  BIND ( IF( ?Sex = "F", "female", "male" ) as ?genderFull )

  # Age, Height, Weight
  BIND ( xsd:integer(?Age) AS ?intAge )
  BIND ( xsd:integer(?Height) AS ?intHeight )
  BIND ( xsd:decimal(?Weight) AS ?decWeight )

  FILTER ( regex(str(?NOC), "AUT") )
}
# LIMIT 10
